#name: linting, testing, building
#run-name: ${{ github.actor }} is learning GitHub Actions
#on: [push]
#jobs:
#  check-bats-version:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '17'
#      - name: install modules
#        run: npm install
#      - name: build production project
#        run: npm run build:prod
#      - name: linting typescript
#        run: npm run lint:ts
#      - name: linting css
#        run: npm run lint:scss
#      - name: unit testing
#        run: npm run test:unit
#      - name: build storybook
#        run: npm run storybook:build
#      - name: screenshot testing
#        run: npm run test:ui:ci



name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: npm install
      - run: npm run build:dev
      - run: npm run lint:ts
      - run: npm run lint:scss
      - run: npm run test:unit
      - run: npm run storybook:build
      - run: npm run test:ui:ci


